export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const TAB_CHEAPEST = 'TAB_CHEAPEST';
export const TAB_FAST = 'TAB_FAST';
export const TAB_OPTIMAL = 'TAB_OPTIMAL';

export const FETCH_TICKETS_START = 'FETCH_TICKETS_START';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';

export const VIEW_MORE = 'VIEW_MORE';
